name: onboarding_ui_challenge
description: An onboarding UI challenge
version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev.0.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  gradient_text: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/computer.png
    - assets/dancing.png
    - assets/hiking.png
    - assets/meditate.png

  fonts:
    - family: Montserrat-Black
      fonts:
        - asset: assets/Montserrat-Black.ttf
    - family: Montserrat-Medium
      fonts:
        - asset: assets/Montserrat-Medium.ttf